name: Aliyun - ACR

run-name: ${{ github.actor }} is syncing images to Aliyun ACR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repos
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Using Skopeo sync images to Aliyun ACR
        run: |
          #!/usr/bin/env bash
          skopeo copy --all docker://ghcr.io/homeassistant/amd64-addon-configurator:5.8.0 docker://registry.cn-hangzhou.aliyuncs.com/${{ github.actor }}/amd64-addon-configurator:5.8.0
