# 工作流名称
name: nvcr.io

# 工作流运行时显示名称
run-name: ${{ github.actor }} is sync nvcr.io to DockerHub.

# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
    
    # 使用shell命令批量同步所需的镜像到dockerHub中
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy --all docker://nvcr.io/nvidia/gpu-operator:v23.9.1                             docker://docker.io/${{ github.actor }}/gpu-operator:v23.9.1
        skopeo copy --all docker://nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.7.1-ubuntu20.04 docker://docker.io/${{ github.actor }}/cuda-sample:vectoradd-cuda11.7.1-ubuntu20.04
        skopeo copy --all docker://nvcr.io/nvidia/k8s/dcgm-exporter:3.2.6-3.1.9-ubuntu20.04        docker://docker.io/${{ github.actor }}/dcgm-exporter:3.2.6-3.1.9-ubuntu20.04
        skopeo copy --all docker://nvcr.io/nvidia/k8s/dcgm-exporter:3.3.0-3.2.0-ubuntu22.04        docker://docker.io/${{ github.actor }}/dcgm-exporter:3.3.0-3.2.0-ubuntu22.04
        skopeo copy --all docker://nvcr.io/nvidia/cloud-native/gpu-operator-validator:v23.9.1      docker://docker.io/${{ github.actor }}/gpu-operator-validator:v23.9.1
        skopeo copy --all docker://nvcr.io/nvidia/cloud-native/k8s-driver-manager:v0.6.5           docker://docker.io/${{ github.actor }}/k8s-driver-manager:v0.6.5
        skopeo copy --all docker://nvcr.io/nvidia/driver:535.129.03-ubuntu20.04                    docker://docker.io/${{ github.actor }}/driver:535.129.03-ubuntu20.04
        skopeo copy --all docker://nvcr.io/nvidia/driver:535.129.03-ubuntu22.04                    docker://docker.io/${{ github.actor }}/driver:535.129.03-ubuntu22.04
        skopeo copy --all docker://nvcr.io/nvidia/driver:450.80.02-ubuntu20.04                     docker://docker.io/${{ github.actor }}/driver:450.80.02-ubuntu20.04
        skopeo copy --all docker://nvcr.io/nvidia/gpu-feature-discovery:v0.8.2-ubi8                docker://docker.io/${{ github.actor }}/gpu-feature-discovery:v0.8.2-ubi8
        skopeo copy --all docker://nvcr.io/nvidia/k8s/container-toolkit:v1.14.3-ubuntu20.04        docker://docker.io/${{ github.actor }}/container-toolkit:v1.14.3-ubuntu20.04
        skopeo copy --all docker://nvcr.io/nvidia/k8s-device-plugin:v0.14.3-ubi8                   docker://docker.io/${{ github.actor }}/k8s-device-plugin:v0.14.3-ubi8
